name: vue-d3-network build
run-name: vue-d3-network build by ${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  vue-d3-network-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run lib:build

      - name: Build
        run: npm run docs:build
